# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'
    - task: Docker@2
      inputs:
        containerRegistry: 'msdemoacr'
        command: 'login'
    - task: Docker@2
      inputs:
       containerRegistry: 'msdemoacr'
       repository: 'frontend'
       command: 'build'
       Dockerfile: '**/Dockerfile'
       tags: 'v1'
    - task: Docker@2
      inputs:
        containerRegistry: 'msdemoacr'
        repository: 'frontend'
        command: 'push'
        tags: 'v1'
    - task: HelmDeploy@0
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionForACR: 'Visual Studio Ultimate with MSDN(920bf6fd-ffb7-4d82-8202-4298a532d21d)'
        azureResourceGroupForACR: 'demorg'
        azureContainerRegistry: 'msdemoacr'
        kubernetesCluster: 'msdemoaks'
        azureResourceGroup: 'demorg'
        azureSubscription: 'Visual Studio Ultimate with MSDN(920bf6fd-ffb7-4d82-8202-4298a532d21d)'
        command: 'install'
        chartType: 'FilePath'
        chartPath: '**/frontendchart'
    