apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-deploy
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-ctr
        image: "{{ .Values.image }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80